/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 923865bfe4d172481f85ce4d593433fd)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		SITE_CONFIG: KVNamespace;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
