import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const root = new URL("../", import.meta.url);
const source = (path) => readFileSync(new URL(path, root), "utf8");

const wrangler = source("wrangler.jsonc");
const worker = source("src/index.ts");
const app = source("public/app.js");
const styles = source("public/styles.css");

test("llr-mariorun has D1 metadata and KV-backed Worker game APIs", () => {
  assert.doesNotMatch(wrangler, /"r2_buckets"\s*:/);
  assert.match(wrangler, /"d1_databases"\s*:/);
  assert.match(wrangler, /"binding"\s*:\s*"GAME_DB"/);
  assert.match(wrangler, /"run_worker_first"\s*:\s*\[[\s\S]*"\/llr-mariorun"/);
  assert.match(wrangler, /"\/llr-mariorun\/\*"/);
  assert.match(worker, /GAME_ASSETS\?: R2Bucket/);
  assert.match(worker, /GAME_DB\?: D1Database/);
  assert.match(worker, /const gameAssetPacksKey = "game:asset-packs"/);
  assert.match(worker, /const gameLevelsKey = "game:levels"/);
  assert.match(worker, /const gameAssetKvPrefix = "game-assets-kv\/"/);
  assert.match(worker, /const gameAssetR2Prefix = "game-assets\/"/);
  assert.match(worker, /const llrMarioRunPath = "\/llr-mariorun"/);
  assert.match(worker, /function defaultLlrMarioRunLink\(\)/);
  assert.match(worker, /async function fetchGameManifest\(request: Request, env: AppEnv\)/);
  assert.match(worker, /async function writeGameAssetPacks\(env: AppEnv, packs: GameAssetPack\[\]\)/);
  assert.match(worker, /async function writeGameLevels\(env: AppEnv, levels: GameLevel\[\]\)/);
  assert.match(worker, /SELECT payload FROM game_asset_packs/);
  assert.match(worker, /INSERT INTO game_levels/);
  assert.match(worker, /assetSlots: gameAssetSlots/);
  assert.match(worker, /async function handleAdminGame\(request: Request, env: AppEnv\)/);
  assert.match(worker, /async function handleGameAssetUpload\(request: Request, env: AppEnv\)/);
  assert.match(worker, /async function fetchGameAsset\(request: Request, env: AppEnv, key: string\)/);
  assert.match(worker, /async function fetchGodotGamePack\(request: Request, env: AppEnv\)/);
  assert.match(worker, /safeUrlSearchParam\(referer, "pack"\)/);
  assert.match(worker, /pack\.id === requestedPackId/);
  assert.match(worker, /async function fetchCompressedGodotWasm\(request: Request, env: AppEnv, origin: string\)/);
  assert.match(worker, /url\.pathname === `\$\{llrMarioRunPath\}\/godot\/index\.pck`/);
  assert.match(worker, /url\.pathname === `\$\{llrMarioRunPath\}\/godot\/index\.wasm`/);
  assert.match(worker, /new DecompressionStream\("gzip"\)/);
  assert.match(worker, /env\.SITE_CONFIG\.put\(key, await file\.arrayBuffer\(\)/);
  assert.match(worker, /env\.SITE_CONFIG\.getWithMetadata/);
  assert.match(worker, /url\.pathname\.startsWith\("\/api\/game\/assets\/"\)/);
});

test("default game content includes asset slots and ten fair long levels", () => {
  assert.match(worker, /const gameAssetSlots: GameAssetSlot\[\] = \[/);
  for (const slot of ["player.idle", "enemy.goomba", "powerup.mushroom", "boss.main", "princess.idle", "audio.bgm", "sm63.player.sheet", "sm63.enemy.goomba.walk", "sm63.pickup.coins", "sm63.audio.title", "game.bundle.pck"]) {
    assert.match(worker, new RegExp(`id: "${slot.replace(".", "\\.")}"`));
  }
  assert.match(worker, /kind: "bundle"/);
  assert.match(worker, /allowedBundleTypes/);
  assert.match(worker, /slot\.kind === "bundle" \? "pck"/);
  assert.match(worker, /\|pck/);
  assert.match(worker, /const defaultGameAssetPacks: GameAssetPack\[\] = \[/);
  assert.match(worker, /const defaultGameLevels: GameLevel\[\] = \[/);
  const levelIds = [...worker.matchAll(/id: "level-[0-9]{2}"/g)].map((match) => match[0]);
  assert.equal(new Set(levelIds).size, 10);
  assert.doesNotMatch(worker, /type: "trap\./);
  assert.match(worker, /checkpoints: \[[\s\S]*?{ x: 600[\s\S]*?{ x: 1800/);
  assert.match(worker, /segments: \[[\s\S]*?"开场"[\s\S]*?"终点"/);
});

test("static llr-mariorun game page embeds Godot runtime with touch controls and mobile rotation", () => {
  assert.equal(existsSync(new URL("public/llr-mariorun/index.html", root)), true);
  assert.equal(existsSync(new URL("public/llr-mariorun/custom.html", root)), false);
  assert.equal(existsSync(new URL("public/llr-mariorun/game.css", root)), true);
  assert.equal(existsSync(new URL("public/llr-mariorun/launcher.js", root)), true);
  for (const file of ["index.html", "index.js", "index.wasm.gz", "index.pck"]) {
    assert.equal(existsSync(new URL(`public/llr-mariorun/godot/${file}`, root)), true);
  }
  assert.equal(existsSync(new URL("public/llr-mariorun/godot/index.wasm", root)), false);

  const html = source("public/llr-mariorun/index.html");
  const css = source("public/llr-mariorun/game.css");
  const launcher = source("public/llr-mariorun/launcher.js");
  const godotLoader = source("public/llr-mariorun/godot/index.js");

  assert.match(html, /老师大冒险/);
  assert.match(html, /GODOT WEB EDITION/);
  assert.doesNotMatch(html, />管理员素材库</);
  assert.match(html, /data-admin-asset-editor hidden/);
  assert.match(html, /href="\/admin\?game=llr-mariorun"/);
  assert.match(html, />素材在线编辑</);
  assert.match(html, /开始前选择/);
  assert.match(html, /id="pack-select"/);
  assert.doesNotMatch(html, /id="level-select"/);
  assert.match(html, /id="start-selected-game"/);
  assert.match(html, /id="reset-game-data"/);
  assert.match(html, /data-reset-game-data/);
  assert.doesNotMatch(html, /id="start-custom-level"/);
  assert.doesNotMatch(html, /试玩编辑关卡/);
  assert.doesNotMatch(html, /选择素材包和关卡/);
  assert.match(html, /src="about:blank"/);
  assert.match(html, /横屏全屏/);
  assert.match(html, /data-key="KeyX"/);
  assert.match(html, /data-key="KeyC"/);
  assert.match(html, /data-key="KeyZ"/);
  assert.match(html, /godot-frame/);
  assert.match(html, /\/llr-mariorun\/godot\/index\.html/);
  assert.match(html, /launcher\.js/);
  assert.match(css, /\.redux-hero/);
  assert.match(css, /\.game-frame-shell/);
  assert.match(css, /\.godot-frame/);
  assert.match(css, /\.virtual-controls/);
  assert.match(css, /\.prelaunch-panel/);
  assert.match(css, /\.launch-buttons/);
  assert.match(css, /body\.game-has-launched \.prelaunch-panel/);
  assert.match(css, /\.virtual-joystick/);
  assert.match(css, /\.joystick-knob/);
  assert.match(css, /body\.game-has-launched:not\(\.is-landscape-fullscreen\) \.game-frame-shell/);
  assert.match(css, /\.is-pressed/);
  assert.match(css, /-webkit-touch-callout:\s*none/);
  assert.match(css, /body\.is-forced-landscape/);
  assert.match(css, /transform:[^;]*rotate\(90deg\)/);
  assert.match(launcher, /fetch\("\/api\/game\/manifest"/);
  assert.match(launcher, /const adminTokenKey = "cloudflare-modular-site\.admin-token"/);
  assert.match(launcher, /function revealAdminAssetEditorLink/);
  assert.match(launcher, /fetch\("\/api\/admin\/game"/);
  assert.match(launcher, /adminAssetEditorLink\.hidden = false/);
  assert.match(launcher, /game\.bundle\.pck/);
  assert.match(launcher, /function renderPrelaunchChoices/);
  assert.match(launcher, /function selectedGameUrl/);
  assert.match(launcher, /function startSelectedGame/);
  assert.match(launcher, /document\.body\.classList\.add\("game-has-launched"\)/);
  assert.match(launcher, /function bindVirtualJoystick/);
  assert.match(launcher, /const movementKeyAliases/);
  assert.match(launcher, /KeyA/);
  assert.match(launcher, /KeyW/);
  assert.match(launcher, /function emitMovementKey/);
  assert.match(launcher, /const horizontalThreshold = radius \* 0\.28/);
  assert.match(launcher, /const verticalThreshold = radius \* 0\.48/);
  assert.match(launcher, /setKey\("ArrowUp", y < -verticalThreshold\)/);
  assert.match(launcher, /setKey\("ArrowDown", y > verticalThreshold\)/);
  assert.match(launcher, /window\.setInterval\(\(\) => \{/);
  assert.match(launcher, /emitMovementKey\(code, "keydown", \{ repeat: true \}\)/);
  assert.match(launcher, /function resetVirtualInputs/);
  assert.match(launcher, /function attachGodotCanvasRecovery/);
  assert.match(launcher, /webglcontextlost/);
  assert.match(launcher, /webglcontextrestored/);
  assert.match(launcher, /window\.addEventListener\("blur", resetVirtualInputs\)/);
  assert.match(launcher, /screen\.orientation\?\.lock\?\.\("landscape-primary"\)/);
  assert.doesNotMatch(launcher, /\/llr-mariorun\/custom\.html/);
  assert.match(launcher, /searchParams\.set\("pack", selectedPackId\)/);
  assert.doesNotMatch(launcher, /searchParams\.set\("level"/);
  assert.doesNotMatch(launcher, /selectedLevelId/);
  assert.doesNotMatch(launcher, /levelSelect/);
  assert.match(launcher, /function resetGameData/);
  assert.match(launcher, /querySelectorAll\("\[data-reset-game-data\]"\)/);
  assert.match(launcher, /indexedDB\.deleteDatabase/);
  assert.match(launcher, /FILE_DATA/);
  assert.match(launcher, /ArrowUp/);
  assert.match(launcher, /KeyX/);
  assert.match(launcher, /KeyC/);
  assert.match(launcher, /KeyZ/);
  assert.match(launcher, /function bindVirtualControls\(\)/);
  assert.match(launcher, /button\.classList\.add\("is-pressed"\)/);
  assert.match(launcher, /new KeyboardEvent\(type/);
  assert.match(launcher, /function requestLandscapeFullscreen/);
  assert.match(launcher, /screen\.orientation\?\.lock\?\.\("landscape"\)/);
  assert.match(godotLoader, /new DecompressionStream\('gzip'\)/);
  assert.match(godotLoader, /WebAssembly\.instantiate\(bytes, imports\)/);
});

test("admin app exposes llr-mariorun entry and online editors", () => {
  assert.match(app, /const llrMarioRunPath = "\/llr-mariorun"/);
  assert.match(app, /function renderAdminGameEditor\(\)/);
  assert.match(app, /function shouldRenderAdminGameEditor\(\)/);
  assert.match(app, /get\("game"\) === "llr-mariorun"/);
  assert.match(app, /function clearAdminGameEditorMode\(\)/);
  assert.match(app, /if \(gameEditorMode\) \{[\s\S]*?main\.append\(renderAdminGameEditor\(\)\)/);
  assert.doesNotMatch(app, /panel\.append\(renderAdminGameEditor\(\)\)/);
  assert.match(app, /async function loadAdminGameConfig\(\)/);
  assert.match(app, /function renderGameAssetPackEditor/);
  assert.match(app, /function importLocalGameAssetPacks/);
  assert.match(app, /function dataUrlToFile/);
  assert.match(app, /function downloadJson/);
  assert.match(app, /function templateAssetForSlot/);
  assert.match(app, /function defaultAssetFilename/);
  assert.match(app, /function findFirstAssetForSlot/);
  assert.match(app, /导入本地素材包/);
  assert.match(app, /下载素材包模板/);
  assert.match(app, /下载当前素材/);
  assert.match(app, /素材在线编辑/);
  assert.match(app, /\.pck,application\/octet-stream/);
  assert.match(app, /function renderGameDataEditor/);
  assert.match(app, /游戏数据保存/);
  assert.doesNotMatch(app, /game-level-designer/);
  assert.doesNotMatch(app, /在线关卡设计/);
  assert.match(app, /\/api\/admin\/game/);
  assert.match(app, /\/api\/admin\/game\/assets/);
  assert.match(app, /老师大冒险/);
  assert.match(styles, /\.game-admin-panel/);
  assert.match(styles, /\.game-editor-tools/);
  assert.match(styles, /\.game-import-button/);
  assert.match(styles, /\.game-asset-slot-grid/);
  assert.doesNotMatch(styles, /\.game-level-designer/);
  assert.doesNotMatch(styles, /\.game-level-preview/);
  assert.doesNotMatch(styles, /\.game-level-object/);
  assert.match(styles, /\.game-level-editor/);
});
